import Navbar from '@/components/navbar/Navbar'
import Footer from '@/components/footer/Footer'
import './globals.css'
import { Inter, Roboto,Poppins } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const roboto = Roboto({ subsets: ['latin','cyrillic-ext'] , weight:['400','900']})


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
       <div className='container'>

        <Navbar /> 
        {children}
      <Footer />
       </div>
       </body>
    </html>
  )
}
